
RUN_DEBUG = True

WEB_SERVER_NAME = 'WebService'
WEB_SERVER_IP = 'localhost'
WEB_SERVER_PORT = 5000

AUDIT_SERVER_NAME = 'AuditService'
AUDIT_SERVER_IP = 'localhost'
AUDIT_SERVER_PORT = 6500

TRIGGER_SERVER_NAME = 'TriggerService'
TRIGGER_SERVER_IP = 'localhost'
TRIGGER_SERVER_PORT = 7000

TRANSACTION_SERVER_NAME = 'TransactionService'
TRANSACTION_SERVER_IP = 'localhost'
TRANSACTION_SERVER_PORT = 6666
TRANSACTION_REDIS_IP = 'localhost'
TRANSACTION_REDIS_PORT = 6379

DATABASE_SERVER_NAME = "DatabaseService"
DATABASE_SERVER_IP = 'localhost'
DATABASE_SERVER_PORT = 5656